# Generated by Django 4.2.17 on 2025-01-02 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventoryitem_category_inventoryitem_date_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='inventory_item_history',
            field=models.TextField(blank=True, null=True),
        ),
    ]
